package tpm

import (
	"context"
	"fmt"

	"github.com/google/go-tpm/tpm2"
)

// GenerateRandom returns `size` number of random bytes generated by the TPM.
func (t *TPM) GenerateRandom(ctx context.Context, size uint16) ([]byte, error) {
	if err := t.Open(goTPMCall(ctx)); err != nil {
		return nil, fmt.Errorf("failed opening TPM: %w", err)
	}
	defer t.Close(ctx)

	r, err := tpm2.GetRandom(t.rwc, size)
	if err != nil {
		return nil, fmt.Errorf("failed generating random data: %w", err)
	}

	if len(r) != int(size) {
		return nil, fmt.Errorf("generated %d random bytes instead of the requested %d", len(r), size)
	}

	return r, nil
}
