name: CI

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "master"
  pull_request:
  workflow:
    secrets:
      GITLEAKS_LICENSE_KEY:
        required: true

jobs:
  ci:
    uses: smallstep/workflows/.github/workflows/goCI.yml@max/gitleaks
    with:
      os-dependencies: "libpcsclite-dev"
      gitleaks: true
      codeql: true
    secrets:
      GITLEAKS_LICENSE_KEY: ${{ secrets.GITLEAKS_LICENSE_KEY }}

